/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ControlPanel: typeof import('@/components/workflow/ControlPanel.vue')['default']
    CustomExecutorConfigForm: typeof import('./components/executor/CustomExecutorConfigForm.vue')['default']
    CustomExecutorForm: typeof import('./components/workflow/sidebar/executor/CustomExecutorForm.vue')['default']
    CustomNode: typeof import('./components/workflow/CustomNode.vue')['default']
    CustomSidebar: typeof import('./components/workflow/CustomSidebar.vue')['default']
    EndNode: typeof import('./components/workflow/node/EndNode.vue')['default']
    ExecutorConfigForm: typeof import('./components/executor/ExecutorConfigForm.vue')['default']
    ExecutorExecuteForm: typeof import('./pages/trigger/components/execute/ExecutorExecuteForm.vue')['default']
    ExecutorNode: typeof import('./components/workflow/node/ExecutorNode.vue')['default']
    ExecutorSidebar: typeof import('./components/workflow/sidebar/ExecutorSidebar.vue')['default']
    FlowExecuteForm: typeof import('./pages/trigger/components/execute/FlowExecuteForm.vue')['default']
    Layout: typeof import('./components/layout/Layout.vue')['default']
    Main: typeof import('./components/layout/Main.vue')['default']
    Menu: typeof import('./components/layout/Menu.vue')['default']
    NavBar: typeof import('./components/layout/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScheduleTriggerForm: typeof import('./pages/trigger/components/trigger/ScheduleTriggerForm.vue')['default']
    StartNode: typeof import('./components/workflow/node/StartNode.vue')['default']
    TriggerNode: typeof import('@/components/workflow/node/TriggerNode.vue')['default']
    TriggerSidebar: typeof import('@/components/workflow/sidebar/TriggerSidebar.vue')['default']
    WebhookTriggerForm: typeof import('./pages/trigger/components/trigger/WebhookTriggerForm.vue')['default']
    WorkerExecutorNode: typeof import('@/components/workflow/node/ExecutorNode.vue')['default']
    Workflow: typeof import('./components/workflow/Workflow.vue')['default']
  }
}
