/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/app/AppList': RouteRecordInfo<'/app/AppList', '/app/AppList', Record<never, never>, Record<never, never>>,
    '/trigger/components/execute/ExecuteConfigForm': RouteRecordInfo<'/trigger/components/execute/ExecuteConfigForm', '/trigger/components/execute/ExecuteConfigForm', Record<never, never>, Record<never, never>>,
    '/trigger/components/execute/ExecutorExecuteForm': RouteRecordInfo<'/trigger/components/execute/ExecutorExecuteForm', '/trigger/components/execute/ExecutorExecuteForm', Record<never, never>, Record<never, never>>,
    '/trigger/components/execute/FlowExecuteForm': RouteRecordInfo<'/trigger/components/execute/FlowExecuteForm', '/trigger/components/execute/FlowExecuteForm', Record<never, never>, Record<never, never>>,
    '/trigger/components/trigger/ScheduleTriggerForm': RouteRecordInfo<'/trigger/components/trigger/ScheduleTriggerForm', '/trigger/components/trigger/ScheduleTriggerForm', Record<never, never>, Record<never, never>>,
    '/trigger/components/trigger/TriggerConfigForm': RouteRecordInfo<'/trigger/components/trigger/TriggerConfigForm', '/trigger/components/trigger/TriggerConfigForm', Record<never, never>, Record<never, never>>,
    '/trigger/components/trigger/WebhookTriggerForm': RouteRecordInfo<'/trigger/components/trigger/WebhookTriggerForm', '/trigger/components/trigger/WebhookTriggerForm', Record<never, never>, Record<never, never>>,
    '/trigger/components/TriggerEditDialog': RouteRecordInfo<'/trigger/components/TriggerEditDialog', '/trigger/components/TriggerEditDialog', Record<never, never>, Record<never, never>>,
    '/trigger/TriggerConfigEdit': RouteRecordInfo<'/trigger/TriggerConfigEdit', '/trigger/TriggerConfigEdit', Record<never, never>, Record<never, never>>,
    '/trigger/TriggerList': RouteRecordInfo<'/trigger/TriggerList', '/trigger/TriggerList', Record<never, never>, Record<never, never>>,
    '/workflow/components/WorkflowEditCommonItem': RouteRecordInfo<'/workflow/components/WorkflowEditCommonItem', '/workflow/components/WorkflowEditCommonItem', Record<never, never>, Record<never, never>>,
    '/workflow/WorkflowList': RouteRecordInfo<'/workflow/WorkflowList', '/workflow/WorkflowList', Record<never, never>, Record<never, never>>,
  }
}
